#! /bin/sh
cp -r ~/.config/bspwm .
cp -r ~/.config/kitty .
cp -r ~/.config/nvim .
cp -r ~/.config/picom .
cp -r ~/.config/polybar .
cp -r ~/.config/rofi .
cp -r ~/.config/sxhkd .
cp -r ~/.config/helix .
cp ~/.zshrc .
cp ~/.zshenv .