#! /bin/sh

cp -r bspwm ~/.config
cp -r helix ~/.config
cp -r kitty ~/.config
cp -r nvim ~/.config
cp -r picom ~/.config
cp -r polybar ~/.config
cp -r rofi ~/.config
cp -r sxhkd ~/.config
cp .zshrc ~
cp .zshenv ~