theme = "molokai"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 20
