theme = "transparent"

[editor]
line-number = "relative"
bufferline = "always"
mouse = false
rulers = [80]
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true
max-wrap = 20

[keys.normal]
