[[language]]
name = "rust"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "java"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
auto-format = true
indent = { tab-width = 4, unit = "    " }
