#!/bin/sh

#
# Colors
#
export DARK="#37352F"
export WHITE_BONE="#D8D0C1"
export SMOKY_BLACK="#100C08"
export PEACH="#FFA570"
export LIGHT_PEACH="#FFCBAD"
export YELLOW="#FFB30F"
export RED="#D72638"
export ORANGE="#ED7D3A"
export PURPLE="#C47AC0"
export YELLOW_GREEN="#B0DB43"
export BLUE="#355691"
export GREEN="#0C7C59"

#
# autostart
#

pgrep -x sxhkd > /dev/null || sxhkd & # shhkd, shortcuts
xsetroot -cursor_name left_ptr & # cursor
/home/kn1ghtress/.fehbg & # wallpaper
~/.config/polybar/launch.sh gummy & # bar
~/.config/picom/launch.sh & # compositor

# 
# bspwm config
#
bspc monitor -d 1 2 3 4 5

bspc config border_radius	0
bspc config border_width	0
bspc config window_gap		10

bspc config top_padding		0
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# bspwm colors
# bspc config focused_border_color \#CFCF88
# bspc config active_border_color \#8C8C44
bspc config focused_border_color \#202020
bspc config active_border_color \#202020
bspc config normal_border_color \#202020

# window rules
bspc rule -a Gimp desktop='^5'
bspc rule -a Chromium desktop='^1'
