hl.on("hyprland.start", function ()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("waybar")
  hl.exec_cmd("$BROWSER")
  hl.exec_cmd("discord")
  hl.exec_cmd("steam")
end)
