cursor            #91cef5
cursor_text_color #00344b

foreground            #dfe3e7
background            #0a0f12
selection_foreground  #20333e
selection_background  #b6c9d8
url_color             #b6c9d8

#: black 000000 767676
color0  #0f1417
color8  #313539
#: red cc0403 f2201f
color1  #0b0d0f
color9  #4d5a66
#: green 19cb00 23fd00
color2  #b6c9d8
color10 #d2e5f4
#: yellow cecb00 fffd00
color3  #cbc1e9
color11 #e7deff
#: blue 0d73cc 1a8fff
color4  #004c6a
color12 #91cef5
#: magenta cb1ed1 fd28ff
color5  #374955
color13 #b6c9d8
#: cyan 0dcdcd 14ffff
color6  #4a4263
color14 #cbc1e9
#: white dddddd ffffff
color7  #c1c7ce
color15 #dfe3e7

mark1_foreground #001e2d
mark1_background #c5e7ff
mark2_foreground #0a1e28
mark2_background #d2e5f4
mark3_foreground #1e1735
mark3_background #e7deff

active_tab_foreground #00344b
active_tab_background #91cef5
inactive_tab_foreground #c5e7ff
inactive_tab_background #004c6a

active_border_color #91cef5
inactive_border_color #00344b
# bell_border_color #ff5a00
