cursor            #eeb4ea
cursor_text_color #4a204c

foreground            #ebdfe6
background            #120d11
selection_foreground  #3c2b3b
selection_background  #d9bfd4
url_color             #d9bfd4

#: black 000000 767676
color0  #171216
color8  #393338
#: red cc0403 f2201f
color1  #a43146
color9  #de909e
#: green 19cb00 23fd00
color2  #d9bfd4
color10 #f6dbf0
#: yellow cecb00 fffd00
color3  #f6b8aa
color11 #ffdad3
#: blue 0d73cc 1a8fff
color4  #633664
color12 #eeb4ea
#: magenta cb1ed1 fd28ff
color5  #544152
color13 #d9bfd4
#: cyan 0dcdcd 14ffff
color6  #663b32
color14 #f6b8aa
#: white dddddd ffffff
color7  #d0c3cc
color15 #ebdfe6

mark1_foreground #320935
mark1_background #ffd6fa
mark2_foreground #261625
mark2_background #f6dbf0
mark3_foreground #33110a
mark3_background #ffdad3

active_tab_foreground #4a204c
active_tab_background #eeb4ea
inactive_tab_foreground #ffd6fa
inactive_tab_background #633664

active_border_color #eeb4ea
inactive_border_color #4a204c
# bell_border_color #ff5a00
