#!/usr/bin/env bash
query="map(select(.description != \"(null)\")) | map({i: .index, desc: .description})"
list=$(pactl -f json list sinks | jq "$query")
choice=$(echo $list | jq ".[].desc" | tr -d "\"" | rofi -dmenu -i -L $(echo $list | jq "length") -W 25%)
index=$(echo $list | jq "map(select(.desc == \"$choice\")) | .[].i")
pactl set-default-sink $index		
